<?php
$username = $_POST['username'];
$userpasswordrc = $_POST['userpassword'];
$userpassword = sha1($userpasswordrc);
$countfile = @ fopen("../user/usercount.wmst", "r");
$usernumber=fgets($countfile);
$usernumber = $usernumber + 1;
fclose($countfile);
$countfile = @ fopen("../user/usercount.wmst", "w");
fwrite($countfile,$usernumber);
fclose($countfile);
$userstring= "\n$usernumber=$username=$userpassword;";
$userdb=fopen("../user/user.wmst","a");
fwrite($userdb,$userstring);
fclose($userdb);
$path="../user/$usernumber";
mkdir(iconv("UTF-8", "GBK", $path),0777,true);
$timenowh=date("H");
$timenowm=date("i");
$timenows=date("s");
$text="$username\n" . date("Y-m-d") . "   " .  $timenowh . ":" .  $timenowm . ":" .  $timenows . "\n$usernumber";
$filenamea = fopen("../user/$usernumber/userinfo.wmst", "w");
fwrite($filenamea, $text);
$text="$username\n" . "No index words" . "\nlv0";
$filenameb = fopen("../user/$usernumber/usersettings.wmst", "w");
fwrite($filenameb, $text);
$text='<?php
$userinfofile = @ fopen("userinfo.wmst", "r") or die("<title>Error 0x00000007</title>Error 0x00000007<br>User info load unsuccessful.");
$usernamerc = fgets($userinfofile);
$addintime = fgets($userinfofile);
$userid= fgets($userinfofile);
fclose($userinfofile);
$userinfofile = @ fopen("usersettings.wmst", "r") or die("<title>Error 0x00000007</title>Error 0x00000007<br>User info load unsuccessful.");
$useraccout = fgets($userinfofile);
$indexwords = fgets($userinfofile);
$userlevel= fgets($userinfofile);
fclose($userinfofile);
$userspacesettings = @ fopen("space.wmst", "r") or die("<title>Error 0x00000008</title>Error 0x00000008<br>User space info load unsuccessful.");
$visitcontrol = fgets($userspacesettings);
fclose($userspacesettings);

echo "<head>";
include("../patterns/autoexec.php");

echo "<title>" . $usernamerc . "_" . $websitename . "</title>";
echo "</head>";
echo "<body>";
include("../patterns/topline.php");
echo "<table class=' . "maindataindex" . '>";
echo "<tr>";
echo "<td>";
echo "";
echo "<img src=' . "./user.png" . ' class=' . "userimage" . '></img>";
echo "<h3>$usernamerc</h3>";
echo "<div>等级 : $userlevel , 入站时间 : $addintime , uid : $userid</div>";
echo "<div>$indexwords</div>";
echo "<pre>";
@ readfile("output.wmst");
echo "</pre>";
echo "</td>";
echo "</tr>";
echo "</table>";
echo "</body>";
?>';
$filenamec = fopen("../user/$usernumber/index.php", "w");
fwrite($filenamec, $text);
$filenamed = fopen("../user/$usernumber/space.wmst", "w");
$text="enable";
fwrite($filenamed, $text);
echo "<meta http-equiv='refresh' content=1;url='./accoutlogin.php'>";
?>
