<?php //By WMProject1217
$filepath = "http://" . $_SERVER['HTTP_HOST'] . "/settings.wmst";
$websitesettings = fopen($filepath, "r") or die("<title>Error 0x00000001</title>Error 0x00000001<br>Website info load unsuccessful.");
$websitename = fgets($websitesettings);
$websiteaddress = fgets($websitesettings);
fclose($websitesettings);

//td.leftline
echo "<table class='leftline'>";
echo "<tr>";
echo "<td>";
echo "<a href='" . $websiteaddress . "/video/wv-1/'>";
echo "<img src='" . $websiteaddress . "/main/picture/wv-1/logo.png' class='videologo'></img>";
echo "<div class='videologotitle'>Bad Apple!!</div>";
echo "</a>";
echo "<a href='" . $websiteaddress . "/video/wv0/'>";
echo "<img src='" . $websiteaddress . "/main/picture/wv0/logo.png' class='videologo'></img>";
echo "<div class='videologotitle'>测试Danmakuplayer</div>";
echo "</a>";
echo "<a href='" . $websiteaddress . "/video/wv1/'>";
echo "<img src='" . $websiteaddress . "/main/picture/wv1/logo.png' class='videologo'></img>";
echo "<div class='videologotitle'>MOPEMOPE</div>";
echo "</a>";
echo "<a href='" . $websiteaddress . "/video/wv2/'>";
echo "<img src='" . $websiteaddress . "/main/picture/wv2/logo.png' class='videologo'></img>";
echo "<div class='videologotitle'>Sad Machine</div>";
echo "</a>";
echo "<a href='" . $websiteaddress . "/read/wr0/'>";
echo "<img src='" . $websiteaddress . "/main/picture/wr0/logo.png' class='videologo'></img>";
echo "<div class='videologotitle'>希灵帝国-远瞳</div>";
echo "</a>";
echo "<a href='" . $websiteaddress . "/read/wr1/'>";
echo "<img src='" . $websiteaddress . "/main/picture/wr1/logo.png' class='videologo'></img>";
echo "<div class='videologotitle'>Untitled</div>";
echo "</a>";
echo "<a href='" . $websiteaddress . "/audio/wa0/'>";
echo "<img src='" . $websiteaddress . "/main/picture/wa0/logo.png' class='videologo'></img>";
echo "<div class='videologotitle'>Music0 00003</div>";
echo "</a>";
echo "<a href='" . $websiteaddress . "/audio/wa1/'>";
echo "<img src='" . $websiteaddress . "/main/picture/wa1/logo.png' class='videologo'></img>";
echo "<div class='videologotitle'>Music24 00012</div>";
echo "</a>";
echo "<a href='" . $websiteaddress . "/audio/wa2/'>";
echo "<img src='" . $websiteaddress . "/main/picture/wa2/logo.png' class='videologo'></img>";
echo "<div class='videologotitle'>Music29 00005</div>";
echo "</a>";
echo "</a>";
echo "</td>";
echo "</tr>";
echo "</table>";
